#!/usr/bin/env bash
#install

sudo apt update --fix-missing
sudo apt install nginx -y
sudo apt install ufw -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
sudo ufw --force enable
#sudo /etc/init.d/nginx start
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
