#!/usr/bin/env bash
# task 9
file='holbertonschool'
if [[ -e $file ]]; then
	echo "holbertonschool file exists"
	if [[ -f $file ]]; then
		echo "holbertonschool is a regular file"
	fi
	if [[ -s $file ]]; then
		echo "holbertonschool is a regular file"
	else
		echo "holbertonschool file is empty"
	fi
else
	echo "holbertonschool file does not exist"
fi

